import { useState } from 'react';
import { Alert,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { cloudConfigured,supabase } from '@/lib/supabase';
import { syncJournal } from '@/lib/cloud-sync';
import { useSQLiteContext } from 'expo-sqlite';

export default function CloudScreen(){
 const db=useSQLiteContext();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [signedIn,setSignedIn]=useState(false);
 const signIn=async()=>{if(!supabase){Alert.alert('Cloud not configured','Add EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY.');return;}setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)Alert.alert('Sign in failed',error.message);else setSignedIn(true)};
 const signUp=async()=>{if(!supabase)return;setBusy(true);const {error}=await supabase.auth.signUp({email,password});setBusy(false);Alert.alert(error?'Sign up failed':'Check your email',error?.message??'Confirm your email, then sign in.')};
 const sync=async()=>{setBusy(true);try{const r=await syncJournal(db);Alert.alert('Sync complete',r.uploaded+' uploaded • '+r.downloaded+' downloaded');}catch(e){Alert.alert('Sync failed',e instanceof Error?e.message:'Unknown error')}finally{setBusy(false)}};
 return <SafeAreaView style={styles.safe}><View style={styles.container}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.eyebrow}>OPTIONAL CLOUD</Text><Text style={styles.title}>Private backup.</Text><Text style={styles.body}>Cloud backup is opt-in. Your local journal remains the primary copy.</Text>{!cloudConfigured?<Text style={styles.warning}>Supabase keys are not configured yet.</Text>:null}{!signedIn?<><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor="#666B76" style={styles.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Password" placeholderTextColor="#666B76" style={styles.input}/><Pressable style={styles.primary} onPress={signIn}><Text style={styles.primaryText}>{busy?'Working…':'Sign in'}</Text></Pressable><Pressable style={styles.secondary} onPress={signUp}><Text style={styles.secondaryText}>Create account</Text></Pressable></>:<Pressable style={styles.primary} onPress={sync}><Text style={styles.primaryText}>{busy?'Syncing…':'Sync private backup'}</Text></Pressable>}</View></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#0B0D12'},container:{flex:1,padding:22},back:{color:'#E7DCE0',fontSize:32},eyebrow:{color:'#C98A9E',fontSize:10,fontWeight:'800',letterSpacing:1.8,marginTop:20},title:{color:'#F7F3F4',fontSize:30,fontWeight:'700',marginTop:8},body:{color:'#8F949E',fontSize:14,lineHeight:21,marginTop:8,marginBottom:24},warning:{color:'#D8A5B3',backgroundColor:'#21171C',padding:12,borderRadius:12,marginBottom:12},input:{backgroundColor:'#151820',borderWidth:1,borderColor:'#292D38',borderRadius:13,color:'#F2EDEF',padding:13,marginTop:10},primary:{backgroundColor:'#C98A9E',borderRadius:13,paddingVertical:14,alignItems:'center',marginTop:16},primaryText:{color:'#1B1216',fontWeight:'800'},secondary:{paddingVertical:14,alignItems:'center'},secondaryText:{color:'#AEB3BD',fontWeight:'700'}});
