import { useEffect,useState } from 'react';
import { Alert,FlatList,Pressable,StyleSheet,Text,View } from 'react-native';
import { router,useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useSQLiteContext } from 'expo-sqlite';
import { deleteEntry,getEntriesForDate,JournalEntry } from '@/db/database';
import { formatLongDate } from '@/lib/calendar';
export default function DayScreen(){const {date}=useLocalSearchParams<{date:string}>();const db=useSQLiteContext();const [entries,setEntries]=useState<JournalEntry[]>([]);const refresh=()=>{if(date)getEntriesForDate(db,date).then(setEntries)};useEffect(refresh,[date,db]);const remove=(e:JournalEntry)=>Alert.alert('Delete this memory?','The local video and its journal entry will be permanently removed from this device.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{await deleteEntry(db,e);refresh()}}]);return <SafeAreaView style={styles.safe}><View style={styles.container}><View style={styles.header}><Pressable style={styles.back} onPress={()=>router.back()}><Text style={styles.backText}>‹</Text></Pressable><View><Text style={styles.eyebrow}>JOURNAL DAY</Text><Text style={styles.title}>{date?formatLongDate(date):'Journal'}</Text></View></View>{entries.length===0?<View style={styles.empty}><Text style={styles.emptyIcon}>○</Text><Text style={styles.emptyTitle}>Nothing recorded yet.</Text><Text style={styles.emptyBody}>This day is waiting for a memory.</Text><Pressable style={styles.recordButton} onPress={()=>router.push('/record')}><Text style={styles.recordText}>Record a memory</Text></Pressable></View>:<FlatList data={entries} keyExtractor={i=>i.id} contentContainerStyle={styles.list} renderItem={({item})=><View style={styles.card}><View><Text style={styles.time}>{new Date(item.entryDate).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text><Text style={styles.duration}>{item.title || item.mood || 'Video journal'}</Text></View><View style={styles.actions}><Pressable style={styles.play} onPress={()=>router.push({pathname:'/entry',params:{id:item.id}})}><Text style={styles.playText}>Play</Text></Pressable><Pressable style={styles.delete} onPress={()=>remove(item)}><Text style={styles.deleteText}>Delete</Text></Pressable></View></View>)}/>}</View></SafeAreaView>;}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#0B0D12'},container:{flex:1,paddingHorizontal:20,paddingTop:10},header:{flexDirection:'row',alignItems:'center',gap:13,marginBottom:24},back:{width:40,height:40,borderRadius:20,backgroundColor:'#171A22',alignItems:'center',justifyContent:'center'},backText:{color:'#E7DCE0',fontSize:29,lineHeight:30},eyebrow:{color:'#C98A9E',fontSize:10,fontWeight:'800',letterSpacing:1.8},title:{color:'#F7F3F4',fontSize:21,fontWeight:'700',marginTop:3},empty:{flex:1,alignItems:'center',justifyContent:'center',paddingBottom:80},emptyIcon:{color:'#6B707B',fontSize:34},emptyTitle:{color:'#EDE8EA',fontSize:18,fontWeight:'700',marginTop:14},emptyBody:{color:'#818691',fontSize:13,marginTop:6},recordButton:{marginTop:22,backgroundColor:'#C98A9E',borderRadius:13,paddingHorizontal:18,paddingVertical:12},recordText:{color:'#1C1216',fontWeight:'800'},list:{gap:10,paddingBottom:30},card:{backgroundColor:'#151820',borderWidth:1,borderColor:'#292D38',borderRadius:16,padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},time:{color:'#F2EDEF',fontSize:16,fontWeight:'700'},duration:{color:'#7F8490',fontSize:11,marginTop:4},actions:{flexDirection:'row',gap:8},play:{backgroundColor:'#C98A9E',borderRadius:10,paddingHorizontal:13,paddingVertical:9},playText:{color:'#1C1216',fontSize:12,fontWeight:'800'},delete:{borderWidth:1,borderColor:'#353944',borderRadius:10,paddingHorizontal:12,paddingVertical:9},deleteText:{color:'#A3A7B1',fontSize:12,fontWeight:'700'}});
