import { useEffect,useState } from 'react';
import { Alert,Pressable,StyleSheet,Text,View } from 'react-native';
import { router,useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { SafeAreaView } from 'react-native-safe-area-context';
import { VideoView,useVideoPlayer } from 'expo-video';
import { deleteEntry,getEntry,JournalEntry } from '@/db/database';
export default function EntryScreen(){const {id}=useLocalSearchParams<{id:string}>();const db=useSQLiteContext();const [entry,setEntry]=useState<JournalEntry|null>(null);useEffect(()=>{if(id)getEntry(db,id).then(setEntry)},[db,id]);const player=useVideoPlayer(entry?.videoUri??null,p=>{p.loop=false});const remove=()=>{if(!entry)return;Alert.alert('Delete this memory?','The video and journal entry will be permanently removed from this device.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{await deleteEntry(db,entry);router.back()}}])};if(!entry)return <SafeAreaView style={styles.safe}><View style={styles.loading}><Text style={styles.loadingText}>Loading memory…</Text></View></SafeAreaView>;return <SafeAreaView style={styles.safe}><View style={styles.container}><View style={styles.header}><Pressable style={styles.back} onPress={()=>router.back()}><Text style={styles.backText}>‹</Text></Pressable><View style={{flex:1}}><Text style={styles.eyebrow}>PRIVATE MEMORY</Text><Text style={styles.title}>{new Date(entry.entryDate).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</Text></View></View><View style={styles.videoWrap}><VideoView player={player} style={styles.video} nativeControls allowsFullscreen contentFit="contain"/></View><View style={styles.info}><View><Text style={styles.infoLabel}>STORAGE</Text><Text style={styles.infoValue}>This device only</Text></View><View><Text style={styles.infoLabel}>STATUS</Text><Text style={styles.secure}>● Private</Text></View></View><Pressable style={styles.delete} onPress={remove}><Text style={styles.deleteText}>Delete this memory</Text></Pressable></View></SafeAreaView>;}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#0B0D12'},container:{flex:1,paddingHorizontal:18,paddingTop:8},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:18},back:{width:40,height:40,borderRadius:20,backgroundColor:'#171A22',alignItems:'center',justifyContent:'center'},backText:{color:'#E7DCE0',fontSize:29,lineHeight:30},eyebrow:{color:'#C98A9E',fontSize:10,fontWeight:'800',letterSpacing:1.8},title:{color:'#F7F3F4',fontSize:18,fontWeight:'700',marginTop:3},videoWrap:{backgroundColor:'#050609',borderRadius:18,overflow:'hidden',borderWidth:1,borderColor:'#282C35',flex:1,maxHeight:560},video:{flex:1},info:{flexDirection:'row',justifyContent:'space-between',paddingVertical:18,paddingHorizontal:4},infoLabel:{color:'#666B77',fontSize:9,fontWeight:'800',letterSpacing:1.5,marginBottom:5},infoValue:{color:'#D6D0D3',fontSize:13},secure:{color:'#8DC8A1',fontSize:13},delete:{borderWidth:1,borderColor:'#4A2A33',borderRadius:13,paddingVertical:13,alignItems:'center',marginBottom:8},deleteText:{color:'#D995A6',fontSize:13,fontWeight:'700'},loading:{flex:1,alignItems:'center',justifyContent:'center'},loadingText:{color:'#A2A6B0'}});
