import { useEffect,useState } from 'react';
import { Alert,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useSQLiteContext } from 'expo-sqlite';
import { getAllEntries } from '@/db/database';

export default function PremiumScreen(){
 const db=useSQLiteContext();const [stats,setStats]=useState({entries:0,minutes:0,days:0,favorite:0});
 useEffect(()=>{getAllEntries(db).then(es=>{const days=new Set(es.map(e=>e.entryDate.slice(0,10)));setStats({entries:es.length,minutes:Math.round(es.reduce((s,e)=>s+(e.durationSeconds??0),0)/60),days:days.size,favorite:es.filter(e=>e.isFavorite).length})})},[db]);
 const recap=()=>Alert.alert('Yearly recap',stats.entries+' memories across '+stats.days+' days. About '+stats.minutes+' minutes of video. '+stats.favorite+' favorites.');
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.eyebrow}>SR JOURNAL PREMIUM</Text><Text style={styles.title}>Remember more. Search better.</Text><Text style={styles.body}>The premium layer is designed around private backup, transcription, deeper search, and yearly recaps.</Text><View style={styles.card}><Text style={styles.cardTitle}>Private Cloud</Text><Text style={styles.cardBody}>Optional Supabase backup with per-user RLS and private storage.</Text><Pressable style={styles.button} onPress={()=>router.push('/cloud')}><Text style={styles.buttonText}>Set up backup</Text></Pressable></View><View style={styles.card}><Text style={styles.cardTitle}>Yearly Recap</Text><Text style={styles.cardBody}>{stats.entries} memories • {stats.days} days • {stats.minutes} minutes</Text><Pressable style={styles.button} onPress={recap}><Text style={styles.buttonText}>Generate recap</Text></Pressable></View><View style={styles.card}><Text style={styles.cardTitle}>Premium roadmap</Text><Text style={styles.feature}>• Transcription and transcript search</Text><Text style={styles.feature}>• AI summaries with explicit consent</Text><Text style={styles.feature}>• Subscription entitlements and storage tiers</Text><Text style={styles.feature}>• Export and full account deletion</Text></View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#0B0D12'},container:{padding:22,paddingBottom:40},back:{color:'#E7DCE0',fontSize:32},eyebrow:{color:'#C98A9E',fontSize:10,fontWeight:'800',letterSpacing:1.8,marginTop:20},title:{color:'#F7F3F4',fontSize:30,fontWeight:'700',marginTop:8},body:{color:'#8F949E',fontSize:14,lineHeight:21,marginTop:8,marginBottom:18},card:{backgroundColor:'#151820',borderWidth:1,borderColor:'#292D38',borderRadius:17,padding:17,marginTop:12},cardTitle:{color:'#F2EDEF',fontSize:16,fontWeight:'800'},cardBody:{color:'#969BA5',fontSize:12,lineHeight:18,marginTop:7},button:{backgroundColor:'#C98A9E',borderRadius:12,paddingVertical:11,alignItems:'center',marginTop:14},buttonText:{color:'#1B1216',fontWeight:'800'},feature:{color:'#AEB3BD',fontSize:12,lineHeight:23,marginTop:5}});
