import { useRef,useState } from 'react';
import { Alert,Pressable,StyleSheet,Text,View } from 'react-native';
import { CameraView,useCameraPermissions,useMicrophonePermissions } from 'expo-camera';
import { router } from 'expo-router';
import * as FileSystem from 'expo-file-system/legacy';
import { useSQLiteContext } from 'expo-sqlite';
import { createEntry } from '@/db/database';
import { makeId } from '@/lib/id';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function RecordScreen(){
 const db=useSQLiteContext();const cameraRef=useRef<CameraView>(null);const [cameraPermission,requestCameraPermission]=useCameraPermissions();const [microphonePermission,requestMicrophonePermission]=useMicrophonePermissions();const [recording,setRecording]=useState(false);const [busy,setBusy]=useState(false);const permissionReady=Boolean(cameraPermission?.granted&&microphonePermission?.granted);
 const requestPermissions=async()=>{const camera=cameraPermission?.granted?cameraPermission:await requestCameraPermission();const mic=microphonePermission?.granted?microphonePermission:await requestMicrophonePermission();if(!camera.granted||!mic.granted)Alert.alert('Permissions required','Camera and microphone access are required to record a journal entry.');};
 const startRecording=async()=>{if(!cameraRef.current||recording||busy)return;setRecording(true);try{const result=await cameraRef.current.recordAsync({maxDuration:3600});if(!result?.uri)return;setBusy(true);const id=makeId();const directory=`${FileSystem.documentDirectory}journal/`;await FileSystem.makeDirectoryAsync(directory,{intermediates:true});const destination=`${directory}${id}.mp4`;await FileSystem.copyAsync({from:result.uri,to:destination});await createEntry(db,{id,entryDate:new Date().toISOString(),videoUri:destination,durationSeconds:null});router.replace({pathname:'/entry',params:{id}});}catch{Alert.alert('Could not save entry','The recording was not saved. Please try again.');}finally{setBusy(false);setRecording(false);}};
 if(!permissionReady)return <SafeAreaView style={styles.safe}><View style={styles.permission}><Text style={styles.logo}>SR JOURNAL</Text><Text style={styles.permissionTitle}>A private camera needs permission.</Text><Text style={styles.permissionBody}>SR Journal records directly to this device. Nothing is uploaded in Stage 1.</Text><Pressable style={styles.primary} onPress={requestPermissions}><Text style={styles.primaryText}>Allow camera & microphone</Text></Pressable><Pressable onPress={()=>router.back()}><Text style={styles.cancel}>Go back</Text></Pressable></View></SafeAreaView>;
 return <View style={styles.safe}><CameraView ref={cameraRef} style={StyleSheet.absoluteFill} facing="front" mode="video"/><View style={styles.overlay}><SafeAreaView style={styles.overlaySafe}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable><View style={styles.headerPill}><Text style={styles.headerText}>{recording?'RECORDING':'READY'}</Text></View><View style={styles.headerSpace}/></View><View style={styles.spacer}/><View style={styles.controls}><Text style={styles.hint}>{busy?'Saving your memory…':recording?'Speak freely. Tap stop when you’re done.':'Your recording stays on this device.'}</Text><Pressable onPress={recording?()=>cameraRef.current?.stopRecording():startRecording} style={[styles.record,recording&&styles.recording]}><View style={[styles.recordInner,recording&&styles.recordInnerRecording]}/></Pressable><Text style={styles.label}>{recording?'STOP':'RECORD'}</Text></View></SafeAreaView></View></View>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#090A0E'},permission:{flex:1,padding:28,justifyContent:'center',alignItems:'center'},logo:{color:'#C98A9E',fontSize:11,fontWeight:'800',letterSpacing:2.5,marginBottom:20},permissionTitle:{color:'#F7F3F4',fontSize:26,fontWeight:'700',textAlign:'center'},permissionBody:{color:'#9095A0',fontSize:14,lineHeight:21,textAlign:'center',marginTop:12,maxWidth:330},primary:{backgroundColor:'#C98A9E',borderRadius:14,paddingHorizontal:20,paddingVertical:14,marginTop:28},primaryText:{color:'#171017',fontWeight:'800',fontSize:14},cancel:{color:'#9B9FAA',marginTop:18,fontSize:13},overlay:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(5,6,9,0.12)'},overlaySafe:{flex:1,paddingHorizontal:18},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},close:{width:42,height:42,borderRadius:21,backgroundColor:'rgba(0,0,0,0.48)',alignItems:'center',justifyContent:'center'},closeText:{color:'#FFF',fontSize:29,fontWeight:'200',marginTop:-3},headerPill:{backgroundColor:'rgba(0,0,0,0.5)',paddingHorizontal:12,paddingVertical:7,borderRadius:14},headerText:{color:'#FFF',fontSize:10,fontWeight:'800',letterSpacing:1.4},headerSpace:{width:42},spacer:{flex:1},controls:{alignItems:'center',paddingBottom:18},hint:{color:'#FFF',fontSize:12,textAlign:'center',marginBottom:18,textShadowColor:'#000',textShadowRadius:5},record:{width:76,height:76,borderRadius:38,borderWidth:5,borderColor:'#FFF',alignItems:'center',justifyContent:'center',backgroundColor:'rgba(0,0,0,0.2)'},recording:{borderColor:'#E5A6B6'},recordInner:{width:58,height:58,borderRadius:29,backgroundColor:'#C84E68'},recordInnerRecording:{width:28,height:28,borderRadius:7,backgroundColor:'#E5A6B6'},label:{color:'#FFF',fontSize:10,fontWeight:'800',letterSpacing:1.7,marginTop:9}});
